version: '3'

#volumes:
#  mysql_data:
#    driver: local

services:
  mysql:
    image: mysql:5.6
    volumes:
      - /var/lib/mysql56-data:/var/lib/mysql
    ports:
      - 3307:3307
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_core_production_star
      MYSQL_USER: star
      MYSQL_PASSWORD: IKi8OvbK1g5PeE6K
#    networks:
#      - my_network
#  keycloak:
#    image: quay.io/keycloak/keycloak:latest
#    environment:
#      DB_VENDOR: MYSQL
#      DB_ADDR: mysql
#      DB_DATABASE: keycloak
#      DB_USER: keycloak
#      DB_PASSWORD: password
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: Pa55w0rd
#      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
#      #JDBC_PARAMS: "connectTimeout=30000"
#    restart: on-failure
#    ports:
#      - 8080:8080
#    networks:
#      - my_network

#networks:
#  my_network:
#    external:
#      name: my_network