version: '3'

volumes:
  mysql_data:
    driver: local

services:
#  mysql:
#    image: mysql:5.7
#    volumes:
#      - mysql_data:/var/lib/mysql
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: keycloak
#      MYSQL_USER: keycloak
#      MYSQL_PASSWORD: password
#    networks:
#      - my_network
  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: H2
#      DB_ADDR: mysql
#      DB_DATABASE: keycloak
#      DB_USER: keycloak
#      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

#      docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -e DB_VENDOR=H2 jboss/keycloak

      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
#      JDBC_PARAMS: "connectTimeout=30000"
    restart: always
    ports:
      - 8080:8080
#    depends_on:
#      - mysql
    networks:
      - my_network

networks:
  my_network:
    external:
      name: my_network